### ISSUE TITLE
[Windows 10 - Thunderbird 60] Windows Task Buttons are Popped out of the Toolbar

### ISSUE THREAD

**Issue by thakyZ** [Aris-t2/CustomizeMyBird#6] opened 2018-06-17 23:38 UTC
The windows task buttons (i.e. Close, Minimize, Maximize) on Windows 10, Thunderbird 60, are popped out of the toolbar area by one pixel. I have taken the liberty to fix this myself.
All you need to do is patch this line from the main style code:
```
@media (-moz-windows-compositor)
@media (-moz-os-version: windows-win10)
    @media (-moz-windows-default-theme)
        :root[tabsintitlebar] #navigation-toolbox
```

With this code:
```
@media (-moz-windows-compositor) {
@media (-moz-os-version: windows-win10) {
    @media (-moz-windows-default-theme) {
        :root[tabsintitlebar] #navigation-toolbox {
	          margin-top: 1px !important;
        }
    }
}
}
```

It works perfectly fine and also can be patched using a userChrome.css file in the chrome folder of the profile.

**Comment by Aris-t2** [comment] 2018-06-18 05:24
Thanks for the fix.

Is this glitch happening with default tabs too or only with "classic squared tabs?

Edit
Could you post a screenshot?

**Comment by Aris-t2** [comment] 2018-06-18 06:43
Could you post a screenshot? I can not reproduce this glitch.

**Comment by Aris-t2** [comment] 2018-06-18 07:37
Install 2.1.3.1 (test build) and tell me, if the issue is still present for you: https://github.com/Aris-t2/CustomizeMyBird/releases/tag/2.1.3

**Comment by thakyZ** [comment] 2018-06-18 12:47
Well I just realized a mistake there was still a border left over from shifting the whole thing down, this is why you shouldn't code late at night.
```
@media (-moz-windows-compositor) {
  @media (-moz-os-version: windows-win10) {
    @media (-moz-windows-default-theme) {
      :root[tabsintitlebar] #navigation-toolbox {
      	margin-top: 0px !important;
      }
      #tabs-toolbar {
        padding-top: 1px !important;
      }
    }
  }
}
```
Leaves no border and everything is neat

**Comment by thakyZ** [comment] 2018-06-18 12:50
EDIT: Your fix doesn't seem to do anything. I forgot to remove my usercontent changes when I backed up the file
Also this is for seemingly sizes equal to or greater than 30.

**Comment by Aris-t2** [comment] 2018-06-18 13:06
I had some glitches with disabled menubar, so I fixed them in version 2.1.3.1.

Keep in mind there are differences depending on menubar visibility (enabled/disabled) and position (above tabs / below tabs) and also tab height settings. Sometimes minimizing/maximizing the window or restarting Tb after a change help to fix some positions.

Post a screenshot of the problem.

**Comment by Aris-t2** [comment] 2018-06-18 13:30
I again replaced 2.1.3.1 and also put it on autoupdate. I could fix caption button position glitches for tab height values above 29px. The overlapping should be gone.

**Comment by thakyZ** [comment] 2018-06-19 17:20
![image](https://user-images.githubusercontent.com/950594/41613357-35907760-73aa-11e8-8817-8b9f4b99d6c4.png)
As you can see from the picture it does work. Although it's nothing like how Firefox works, but it's a good temporary solution for now
Firefox:
![image](https://user-images.githubusercontent.com/950594/41613344-2b6e7e80-73aa-11e8-8d9d-738e352c62ff.png)

**Comment by Aris-t2** [comment] 2018-06-20 10:16
Firefox does not apply different button dimensions to caption buttons depending on menubars visibility. No idea why Tb devs took this path.

**Comment by Aris-t2** [comment] 2018-06-20 12:21
I'm trying a different approach to handle caption buttons and tab height settings. Caption buttons height will be connected to tab height for tabs smaller than 32px.

The current 2.1.3.3 build is experimental and has to be installed manually:
https://github.com/Aris-t2/CustomizeMyBird/releases/tag/2.1.3

**Comment by Aris-t2** [comment] 2018-06-21 08:02
Can we close this for now or is "this" still an issue in 2.1.4? I have no plans to handle caption buttons differently than now for tab height values below 32px. "Todays" build of 2.1.4 also allows tab height values of 24px.

Win10s default top/bottom paddings are set to 9px by Thunderbird. CMB overrides the 9px for tab sizes below 32px like this: **min(9px,9px - (32px-tabheight))**.
e.g.
Custom tab height of 28px:
min(9px,9px - (32px-28px)) = min(9px,5px)) -> 5px (caption buttons top/bottom paddings)
Custom tab height of 24px:
min(9px,9px - (32px-24px)) = min(9px,1px)) -> 1px (caption buttons top/bottom paddings)
Custom tab height of 36px:
min(9px,9px - (32px-36px)) = min(9px,13px)) -> 9px (caption buttons top/bottom paddings)

All this works fine on Windows 7-10 and Linux. I have not tested macOS yet.

**Comment by thakyZ** [comment] 2018-06-26 01:43
Sure

**Closed as completed** 2018-06-26 01:43 UTC

**Comment by Aris-t2** [comment] 2018-06-26 08:41
Thanks,
If something comes up again, feel free to reopen this again.
